// <auto-generated />
namespace Sitemaker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class asdadkk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asdadkk));
        
        string IMigrationMetadata.Id
        {
            get { return "201608141458100_asdadkk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
