// <auto-generated />
namespace Sitemaker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class siteid1234556 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(siteid1234556));
        
        string IMigrationMetadata.Id
        {
            get { return "201608192020255_siteid1234556"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
